#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMConsultantsDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MasianoJanzebConsultants")]
	public partial class JMConsultantsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public JMConsultantsDataContext() : 
				base(global::JMConsultantsDB.Properties.Settings.Default.MasianoJanzebConsultantsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public JMConsultantsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JMConsultantsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JMConsultantsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public JMConsultantsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sproc_tblGP_Get_GP_numbers")]
		public ISingleResult<sproc_tblGP_Get_GP_numbersResult> sproc_tblGP_Get_GP_numbers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sproc_tblGP_Get_GP_numbersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sproc_GetMedicalSchoolDetails")]
		public ISingleResult<sproc_GetMedicalSchoolDetailsResult> sproc_GetMedicalSchoolDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MedicalSchoolCode", DbType="VarChar(4)")] string medicalSchoolCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), medicalSchoolCode);
			return ((ISingleResult<sproc_GetMedicalSchoolDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sproc_tblGP_Get_GPName_and_MedSchool")]
		public ISingleResult<sproc_tblGP_Get_GPName_and_MedSchoolResult> sproc_tblGP_Get_GPName_and_MedSchool([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GPNo", DbType="Int")] System.Nullable<int> gPNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gPNo);
			return ((ISingleResult<sproc_tblGP_Get_GPName_and_MedSchoolResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sproc_tblPracticeGP_Get_PracticeGPNos")]
		public ISingleResult<sproc_tblPracticeGP_Get_PracticeGPNosResult> sproc_tblPracticeGP_Get_PracticeGPNos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sproc_tblPracticeGP_Get_PracticeGPNosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sproc_tblPracticeGP_Get_HighesPracticeGPNo")]
		public ISingleResult<sproc_tblPracticeGP_Get_HighesPracticeGPNoResult> sproc_tblPracticeGP_Get_HighesPracticeGPNo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sproc_tblPracticeGP_Get_HighesPracticeGPNoResult>)(result.ReturnValue));
		}
	}
	
	public partial class sproc_tblGP_Get_GP_numbersResult
	{
		
		private int _JM_GPNo;
		
		public sproc_tblGP_Get_GP_numbersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_GPNo", DbType="Int NOT NULL")]
		public int JM_GPNo
		{
			get
			{
				return this._JM_GPNo;
			}
			set
			{
				if ((this._JM_GPNo != value))
				{
					this._JM_GPNo = value;
				}
			}
		}
	}
	
	public partial class sproc_GetMedicalSchoolDetailsResult
	{
		
		private string _JM_MedicalSchoolCode;
		
		private string _JM_Name;
		
		private string _JM_University;
		
		private System.Nullable<int> _JM_Established;
		
		private string _JM_Comments;
		
		private string _JM_Award;
		
		public sproc_GetMedicalSchoolDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_MedicalSchoolCode", DbType="Char(4) NOT NULL", CanBeNull=false)]
		public string JM_MedicalSchoolCode
		{
			get
			{
				return this._JM_MedicalSchoolCode;
			}
			set
			{
				if ((this._JM_MedicalSchoolCode != value))
				{
					this._JM_MedicalSchoolCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_Name", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string JM_Name
		{
			get
			{
				return this._JM_Name;
			}
			set
			{
				if ((this._JM_Name != value))
				{
					this._JM_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_University", DbType="VarChar(50)")]
		public string JM_University
		{
			get
			{
				return this._JM_University;
			}
			set
			{
				if ((this._JM_University != value))
				{
					this._JM_University = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_Established", DbType="Int")]
		public System.Nullable<int> JM_Established
		{
			get
			{
				return this._JM_Established;
			}
			set
			{
				if ((this._JM_Established != value))
				{
					this._JM_Established = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_Comments", DbType="VarChar(500)")]
		public string JM_Comments
		{
			get
			{
				return this._JM_Comments;
			}
			set
			{
				if ((this._JM_Comments != value))
				{
					this._JM_Comments = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_Award", DbType="VarChar(10)")]
		public string JM_Award
		{
			get
			{
				return this._JM_Award;
			}
			set
			{
				if ((this._JM_Award != value))
				{
					this._JM_Award = value;
				}
			}
		}
	}
	
	public partial class sproc_tblGP_Get_GPName_and_MedSchoolResult
	{
		
		private string _JM_Name;
		
		private string _JM_MedicalSchoolCode;
		
		public sproc_tblGP_Get_GPName_and_MedSchoolResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_Name", DbType="VarChar(200)")]
		public string JM_Name
		{
			get
			{
				return this._JM_Name;
			}
			set
			{
				if ((this._JM_Name != value))
				{
					this._JM_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_MedicalSchoolCode", DbType="Char(4)")]
		public string JM_MedicalSchoolCode
		{
			get
			{
				return this._JM_MedicalSchoolCode;
			}
			set
			{
				if ((this._JM_MedicalSchoolCode != value))
				{
					this._JM_MedicalSchoolCode = value;
				}
			}
		}
	}
	
	public partial class sproc_tblPracticeGP_Get_PracticeGPNosResult
	{
		
		private int _JM_PracticeGPNo;
		
		public sproc_tblPracticeGP_Get_PracticeGPNosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JM_PracticeGPNo", DbType="Int NOT NULL")]
		public int JM_PracticeGPNo
		{
			get
			{
				return this._JM_PracticeGPNo;
			}
			set
			{
				if ((this._JM_PracticeGPNo != value))
				{
					this._JM_PracticeGPNo = value;
				}
			}
		}
	}
	
	public partial class sproc_tblPracticeGP_Get_HighesPracticeGPNoResult
	{
		
		private System.Nullable<int> _maxJM_PracticeGPNo;
		
		public sproc_tblPracticeGP_Get_HighesPracticeGPNoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxJM_PracticeGPNo", DbType="Int")]
		public System.Nullable<int> maxJM_PracticeGPNo
		{
			get
			{
				return this._maxJM_PracticeGPNo;
			}
			set
			{
				if ((this._maxJM_PracticeGPNo != value))
				{
					this._maxJM_PracticeGPNo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
